basePath: /api/v1/
definitions:
  app.HealthCheckResponse:
    properties:
      status:
        example: healthy
        type: string
      timestamp:
        example: "2023-10-27T10:00:00Z"
        type: string
    type: object
  domain.RegistrationRequest:
    properties:
      email:
        type: string
      family_name:
        minLength: 2
        type: string
      name:
        maxLength: 12
        minLength: 2
        type: string
      password:
        minLength: 12
        type: string
      password_confirmation:
        type: string
      phone:
        type: string
    required:
    - email
    - family_name
    - name
    - password
    - password_confirmation
    - phone
    type: object
  domain.RequestResponse:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
  domain.TokensPair:
    properties:
      access_token:
        type: string
      refresh_token:
        type: string
    type: object
  handlers.LoginDTO:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  handlers.RefreshReq:
    properties:
      refresh_token:
        type: string
    required:
    - refresh_token
    type: object
  handlers.successRegistration:
    properties:
      id:
        type: string
      message:
        default: Registration successful
        type: string
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: petbackend-a2vg.onrender.com
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /health:
    get:
      consumes:
      - application/json
      description: Checks if the application is running and responsive.
      produces:
      - application/json
      responses:
        "200":
          description: Application is healthy
          schema:
            $ref: '#/definitions/app.HealthCheckResponse'
        "503":
          description: Application is unhealthy or service unavailable
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Performs a health check on the application
      tags:
      - System
  /oauth/{provider}:
    get:
      consumes:
      - application/json
      description: Handles the callback from an OAuth2.0 provider after user authentication.
      parameters:
      - description: OAuth2.0 provider name (e.g., google, github)
        in: path
        name: provider
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: Successfully authenticated and generated tokens
          schema:
            $ref: '#/definitions/domain.TokensPair'
        "404":
          description: Account with this email not found
          schema:
            $ref: '#/definitions/domain.RequestResponse'
        "500":
          description: Internal server error or failed to complete OAuth2.0 authentication
          schema:
            $ref: '#/definitions/domain.RequestResponse'
      summary: OAuth2.0 Provider Callback
      tags:
      - OAuth
  /specialist/login:
    post:
      consumes:
      - application/json
      description: Login specialist
      parameters:
      - description: Login request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handlers.LoginDTO'
      produces:
      - application/json
      responses:
        "200":
          description: Login succeeded
          schema:
            $ref: '#/definitions/domain.TokensPair'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/domain.RequestResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/domain.RequestResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/domain.RequestResponse'
      summary: Login
      tags:
      - Specialist
  /specialist/register:
    post:
      consumes:
      - application/json
      description: New specialist registration
      parameters:
      - description: Registration request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/domain.RegistrationRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Sign in succeeded
          schema:
            $ref: '#/definitions/handlers.successRegistration'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/domain.RequestResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/domain.RequestResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/domain.RequestResponse'
      summary: Registration
      tags:
      - Specialist
  /token/refresh:
    post:
      consumes:
      - application/json
      description: Exchanges a valid refresh token for a new access token and a new
        refresh token.
      parameters:
      - description: Refresh token request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handlers.RefreshReq'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully generated new token pair
          schema:
            $ref: '#/definitions/domain.TokensPair'
        "400":
          description: Invalid request payload or malformed refresh token
          schema:
            $ref: '#/definitions/domain.RequestResponse'
        "401":
          description: 'Unauthorized: Invalid refresh token signature or expired'
          schema:
            $ref: '#/definitions/domain.RequestResponse'
        "403":
          description: 'Forbidden: Refresh token has been revoked'
          schema:
            $ref: '#/definitions/domain.RequestResponse'
        "500":
          description: Internal server error due to token validation, database lookup,
            or token generation/revocation issues
          schema:
            $ref: '#/definitions/domain.RequestResponse'
      summary: Update access and refresh tokens
      tags:
      - Token
schemes:
- https
securityDefinitions:
  Bearer:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
